apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: liftbridgeclusters.liftbridge.io
spec:
  additionalPrinterColumns:
  - description: Time elapsed since the creation of the cluster.
    JSONPath: .metadata.creationTimestamp
    name: Age
    priority: 0
    type: date
  - description: Whether synchronisation of the resource is currently paused.
    JSONPath: .spec.paused
    name: Paused
    priority: 1
    type: boolean
  - description: The number of replicas in the cluster.
    JSONPath: .spec.replicas
    name: Replicas
    priority: 0
    type: integer
  - description: The version of Liftbridge running in the cluster.
    JSONPath: .spec.version
    name: Version
    priority: 0
    type: string
  group: liftbridge.io
  names:
    categories:
    - all
    listKind: LiftbridgeClusterList
    kind: LiftbridgeCluster
    plural: liftbridgeclusters
    singular: liftbridgecluster
    shortNames:
    - lc
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    scale:
      labelSelectorPath: .status.selector
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            logLevel:
              type: string
            nats:
              type: object
              properties:
                servers:
                  items:
                    type: string
                  type: array
            paused:
              type: boolean
            replicas:
              type: integer
            storage:
              type: object
              properties:
                sizeGB:
                  type: integer
                storageClassName:
                  type: string
            tls:
              type: object
              properties:
                secretName:
                  type: string
            version:
              type: string
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
